<?php

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Public, no-login rider page for Salibay last-mile deliveries — the short
 * version of the fleet trip flow (fleet/trips/driver_gps): no vehicle,
 * odometer, or GPS tracking, just Start Delivery -> Delivered/Cancelled.
 * Access is by the same opaque per-shipment token pattern fleet trips use,
 * generated by Shipments::_get_or_create_driver_token().
 */
class Salibay_delivery extends App_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->helper('courier_goshipping/courier');

        // Self-heal: this controller's own rider page (and the waybill link
        // that generates it) both depend on these columns existing, but the
        // module deploy that ships this code may land before install.php's
        // migration has actually run against the live DB.
        if ($this->db->table_exists(db_prefix() . '_shipments')) {
            if (!$this->db->field_exists('driver_token', db_prefix() . '_shipments')) {
                $this->db->query('ALTER TABLE `' . db_prefix() . '_shipments` ADD COLUMN `driver_token` VARCHAR(64) NULL DEFAULT NULL, ADD UNIQUE KEY `driver_token` (`driver_token`)');
            }
            if (!$this->db->field_exists('cancel_reason', db_prefix() . '_shipments')) {
                $this->db->query('ALTER TABLE `' . db_prefix() . '_shipments` ADD COLUMN `cancel_reason` TEXT NULL DEFAULT NULL');
            }
        }
        if ($this->db->table_exists(db_prefix() . '_shipment_status_history') && !$this->db->field_exists('notes', db_prefix() . '_shipment_status_history')) {
            $this->db->query('ALTER TABLE `' . db_prefix() . '_shipment_status_history` ADD COLUMN `notes` TEXT NULL DEFAULT NULL');
        }
    }

    private function _get_shipment_by_token($token)
    {
        if (!$token) {
            return null;
        }
        return $this->db->where('driver_token', $token)->get(db_prefix() . '_shipments')->row();
    }

    public function rider($token)
    {
        $shipment = $this->_get_shipment_by_token($token);
        if (!$shipment) {
            echo 'Invalid or expired delivery link.';
            return;
        }

        $order = $this->db->where('gs_shipment_id', $shipment->id)->get(db_prefix() . 'shopify_orders')->row();

        $items_summary = '-';
        if ($order && $this->db->table_exists(db_prefix() . 'shopify_order_items')) {
            $items = $this->db->select("GROUP_CONCAT(CONCAT(COALESCE(NULLIF(product_name, ''), 'Product'), ' (x', quantity, ')') SEPARATOR ', ') AS items_summary")
                ->where('shopify_order_id', $order->id)
                ->get(db_prefix() . 'shopify_order_items')
                ->row();
            $items_summary = $items && $items->items_summary ? $items->items_summary : '-';
        }

        $recipient = $this->db->where('id', $shipment->recipient_id)->get(db_prefix() . '_shipment_recipients')->row();

        $data['title']         = 'Salibay Delivery';
        $data['token']         = $token;
        $data['shipment']      = $shipment;
        $data['order']         = $order;
        $data['items_summary'] = $items_summary;
        $data['recipient']     = $recipient;

        $this->load->view('salibay_delivery/rider', $data);
    }

    /**
     * Forward-only status advance — mirrors fleet/Trips::_advance_shipment_status()
     * so a rider tapping a step twice, or out of order, never regresses a
     * shipment that's already further along.
     */
    private function _advance_shipment_status($shipment_id, $new_status_id)
    {
        $shipment = $this->db->select('id, status_id')->where('id', $shipment_id)->get(db_prefix() . '_shipments')->row();
        if (!$shipment || (int) $shipment->status_id >= $new_status_id) {
            return;
        }

        $this->db->where('id', $shipment_id)->update(db_prefix() . '_shipments', ['status_id' => $new_status_id]);
        // No login on this token-based link — the assigned staff/agent (set
        // via Assign Agent/Staff) is the best identity available for "who
        // did this" on the shipment's timeline.
        $assigned = $this->db->select('s.staff_id, st.firstname, st.lastname')
            ->from(db_prefix() . '_shipments s')
            ->join(db_prefix() . 'staff st', 'st.staffid = s.staff_id', 'left')
            ->where('s.id', $shipment_id)
            ->get()
            ->row();
        $this->db->insert(db_prefix() . '_shipment_status_history', [
            'shipment_id'         => $shipment_id,
            'status_id'           => $new_status_id,
            'changed_at'          => date('Y-m-d H:i:s'),
            'changed_by_staff_id' => $assigned->staff_id ?? null,
            'changed_by_label'    => $assigned && $assigned->firstname ? trim($assigned->firstname . ' ' . $assigned->lastname) . ' (Rider link)' : 'Rider link',
        ]);
    }

    private function _mirror_salibay_order_status($shipment_id, $order_status)
    {
        if ($this->db->table_exists(db_prefix() . 'shopify_orders')) {
            $this->db->where('gs_shipment_id', $shipment_id)->update(db_prefix() . 'shopify_orders', [
                'order_status' => $order_status,
            ]);
        }
    }

    /**
     * Pushes the real Shopify fulfillment/tracking update, not just our own
     * local order_status mirror — must never block the rider's action if
     * Shopify's API hiccups.
     */
    private function _push_shopify_status($shipment_id, $status_id)
    {
        try {
            $this->load->model('shopify_connector/shopify_connector_model');
            $this->shopify_connector_model->push_shopify_fulfillment_status($shipment_id, $status_id);
        } catch (\Throwable $e) {
            log_message('error', 'Shopify fulfillment push crashed: ' . $e->getMessage());
        }
    }

    // ── Rider taps "Start Delivery" — parcel is in hand, heading out (public POST)
    public function start()
    {
        header('Content-Type: application/json');

        $shipment = $this->_get_shipment_by_token($this->input->post('token'));
        if (!$shipment) {
            echo json_encode(['success' => false, 'message' => 'Invalid delivery link.']);
            return;
        }

        $this->_advance_shipment_status($shipment->id, 5); // in_transit
        $this->_mirror_salibay_order_status($shipment->id, 'processing');
        $this->_push_shopify_status($shipment->id, 5);

        echo json_encode(['success' => true]);
    }

    // ── Rider confirms delivery with the customer's on-screen signature (public POST)
    public function deliver()
    {
        header('Content-Type: application/json');

        $shipment = $this->_get_shipment_by_token($this->input->post('token'));
        if (!$shipment) {
            echo json_encode(['success' => false, 'message' => 'Invalid delivery link.']);
            return;
        }

        $first_name = trim((string) $this->input->post('first_name'));
        $last_name  = trim((string) $this->input->post('last_name'));
        $signature  = $this->input->post('signature');

        if ($first_name === '' || $last_name === '' || empty($signature)) {
            echo json_encode(['success' => false, 'message' => "Please enter the customer's name and have them sign."]);
            return;
        }

        $canvas_data = str_replace(' ', '+', str_replace('data:image/png;base64,', '', $signature));
        $image_data  = base64_decode($canvas_data);
        if ($image_data === false) {
            echo json_encode(['success' => false, 'message' => 'Could not read the signature. Please try again.']);
            return;
        }

        $signatures_dir = FCPATH . 'modules/courier_goshipping/assets/deliveries/signatures/';
        if (!is_dir($signatures_dir)) {
            @mkdir($signatures_dir, 0755, true);
        }
        $file_name = uniqid('salibay_delivery_') . '.png';
        if (!file_put_contents($signatures_dir . $file_name, $image_data)) {
            echo json_encode(['success' => false, 'message' => 'Could not save the signature. Please try again.']);
            return;
        }

        courier_load_model('Delivery_model');
        $this->Delivery_model->add([
            'shipment_id'   => $shipment->id,
            'first_name'    => $first_name,
            'last_name'     => $last_name,
            'signature_url' => 'assets/deliveries/signatures/' . $file_name,
        ]);

        $this->_advance_shipment_status($shipment->id, 8); // delivered
        $this->_mirror_salibay_order_status($shipment->id, 'delivered');
        $this->_push_shopify_status($shipment->id, 8);

        echo json_encode(['success' => true]);
    }

    // ── Rider cancels the delivery with a reason (public POST)
    public function cancel()
    {
        header('Content-Type: application/json');

        $shipment = $this->_get_shipment_by_token($this->input->post('token'));
        if (!$shipment) {
            echo json_encode(['success' => false, 'message' => 'Invalid delivery link.']);
            return;
        }

        $reason = trim((string) $this->input->post('reason'));
        if ($reason === '') {
            echo json_encode(['success' => false, 'message' => 'Please enter a reason for cancelling.']);
            return;
        }

        $cancelled_status = $this->db->where('status_name', 'cancelled')->get(db_prefix() . '_shipment_statuses')->row();
        $cancelled_status_id = $cancelled_status ? (int) $cancelled_status->id : 9;

        $this->db->where('id', $shipment->id)->update(db_prefix() . '_shipments', [
            'status_id'     => $cancelled_status_id,
            'cancel_reason' => $reason,
        ]);
        $assigned = $this->db->select('firstname, lastname')->where('staffid', $shipment->staff_id)->get(db_prefix() . 'staff')->row();
        $this->db->insert(db_prefix() . '_shipment_status_history', [
            'shipment_id'         => $shipment->id,
            'status_id'           => $cancelled_status_id,
            'notes'               => $reason,
            'changed_at'          => date('Y-m-d H:i:s'),
            'changed_by_staff_id' => $shipment->staff_id ?: null,
            'changed_by_label'    => $assigned ? trim($assigned->firstname . ' ' . $assigned->lastname) . ' (Rider link)' : 'Rider link',
        ]);
        $this->_mirror_salibay_order_status($shipment->id, 'cancelled');
        $this->_push_shopify_status($shipment->id, $cancelled_status_id);

        echo json_encode(['success' => true]);
    }
}
